### ISSUE TITLE
New Domain

### ISSUE THREAD

**Issue by pck928** [JakeLardinois/DoorCountyAA#12]
Jake the District has agreed to update the Domain/URL to include Kewaunee and use the current http://doorcountyaa.org/ pass through like you did the previous doorcountyaa.com.  We would like to close out the doorcounty.com domain when it comes up for renewal which I believe is 18 months from now.

I am thinking something like door-kewaunee-aa.org or maybe just District22.org.  Do you know much about how search engines work in relation to the url?  The first option seems more obvious to people that don't know we are in District 22, but maybe the url doesn't matter in searching?

Feel free to give me a call or schedule a meeting if you want to discuss.

**Comment by JakeLardinois** [comment]
The url doesn't really make a difference to the search engines; the content matters the most.  Having the SSL cert on doorcountyaa.org will be impactful.
Let me know the domain you would like and I'll set it up along with the cert purchase.

**Comment by pck928** [comment]
Let's go with door_kewaunee_aa.org.  Thank you!!

**Comment by JakeLardinois** [comment]
The underscores are not allowed in domain names.  I do see that "doorkewauneeaa.org" is available.  Does that one work?

**Comment by pck928** [comment]
Yes that works, thanks!Thank you! Pamela ***@***.*** Apr 12, 2023, at 2:11 PM, Jake Lardinois ***@***.***> wrote:﻿
The underscores are not allowed in domain names.  I do see that "doorkewauneeaa.org" is available.  Does that one work?

**Comment by JakeLardinois** [comment]
The domain has been purchased and the site reconfigured to utilize DoorKewauneeAA.org.

**Comment by pck928** [comment]
Hello!  Just wanted to let you know we are traveling for another 10 days so I won’t be able to look at any of this or get a check sent to you until the 15th (Ron, the treasurer is my husband).  Thank you!!!Thank you! Pamela ***@***.*** May 4, 2023, at 10:21 AM, Jake Lardinois ***@***.***> wrote:﻿
The domain has been purchased and the site reconfigured to utilize DoorKewauneeAA.org.
