### ISSUE TITLE
District 22 Homepage

### ISSUE THREAD

**Issue by pck928** [JakeLardinois/DoorCountyAA#13]
At the last District 22 meeting we agreed to do some updates to the District 22 website (with your help ;-)

On the home page we would like to change the heading to read
"Alcoholics Anonymous District 22 - Serving Door and Kewaunee Counties" (remove the Door County AA)

If possible, change the Big Book Icon for the current dust cover version.
Update the language in the preamble to "people", instead of "men and women" as it is now written in the Grapevine. 
Increase the font on the preamble.

Move the Meeting App information to the meeting listing page - if possible add the Meeting App Icon to the description.

**Comment by pck928** [comment]
Also, I think you can remove the "Home Page" label above the Big Book icon.

**Comment by JakeLardinois** [comment]
Heading has been updated.
Preamble verbiage has been updated.
The page Titles (ie "Home Page") have been removed.
Meeting App link has been moved to the links page.

Lastly, please provide the image you would like me to utilize in place of the current Big Book and I'll close out this task.

**Comment by pck928** [comment]
Thank you so much! 
This is the current Big Book image.




    On Thursday, May 4, 2023 at 10:51:43 AM CDT, Jake Lardinois ***@***.***> wrote:  
 
 


Heading has been updated.
Preamble verbiage has been updated.
The page Titles (ie "Home Page") have been removed.
Meeting App link has been moved to the links page.

Lastly, please provide the image you would like me to utilize in place of the current Big Book and I'll close out this task.

**Comment by JakeLardinois** [comment]
You may need to email me the image directly.  I don't see a way to attache images to this ticket and I didn't recieve an image from your post...

**Comment by JakeLardinois** [comment]
Big book image has been updated.
