### ISSUE TITLE
Links Page

### ISSUE THREAD

**Issue by pck928** [JakeLardinois/DoorCountyAA#15]
On the Links Page:
1. The link to the meeting list isn't dynamic so it is very outdated.  The request to allow for exporting to .PDF file in the Meeting List ticket should address this so I think this link can be removed.
2. The Wisconsin Intergroup link doesn't work.  I am not sure where that list would actually be kept up to date so it is probably best to remove the link.
3. If possible, increase the font on all of the links and maybe underline them so people know they can be clicked on.
4. If there is a way to update the link easily then I would like to have a link for the Now and Then newsletter that the PI person can update each month.

**Comment by JakeLardinois** [comment]
Wisconsin intergroup link is removed.
Fonts increased
links are now underlined with blue text.
The links page is easily editable via wordpress ui. If you would like me to add a specific link please provide it via a ticket.

The pdf export may be a bit tricky.  I'll look into that further under task #14
