### ISSUE TITLE
Home Page - District 22 Information

### ISSUE THREAD

**Issue by pck928** [JakeLardinois/DoorCountyAA#16]
We need to add the District 22 Information to the Website and I think it would be most helpful if it was on the Home Page, however I am not sure there is space.

District Meeting Information:
1st Thursday of Each Month @ 6pm
115 Club
115 North 5th Avenue
Sturgeon Bay, WI 54235 United States

Zoom
Web: [https://us04web.zoom.us/j/3994175176](https://us04web.zoom.us/j/3994175176%C2%A0)
Code: 3994175176
Passcode: 115

7th Tradition - Group Donations to District 22 can be sent to:
District 22 
P.O. Box 558
Sturgeon Bay, WI 54235-0558

Donations to the District support AA service activities such as providing Big Books to the local corrections facilities, libraries and schools.  If you have suggestions on how our District can better support the alcoholics in our community, please attend our monthly meeting or email us at webmaster@doorcountyaa.org.

**Comment by JakeLardinois** [comment]
note that webmaster@doorcountyaa.org is still functional but will be replaced with webmaster@doorkewauneeaa.org

**Comment by JakeLardinois** [comment]
District 22 Meeting info is on the bottom of the Meetings page.
Homepage is updated with the Donation info.
